### ISSUE TITLE
Add scripting rule access in decision table output cell function list

### ISSUE THREAD

**Issue by t4keo** [decisiongrid/Issues#11]
I would like to be able to use scripting rule in decision table output cell function.

N.B. : I know that I can do something like {price}*2 in the output cell but this is to explain my request in a clearer way.
Example : 
- I have a scripting rule called Multiply (the sample one) with a function multiply inside.
- I create a decision table and have a price input, a condition input, and a price output
- In my output, I choose function mode and select Multiply (or multiply if we can insert a custom key or even TIMES if we can insert a custom mapping to use in decision table) and finish my output function so it looks like Multiply({value1: {price}, value2: 2}) (or with custom key multiply({value1: {price}, value2: 2}) or with custom mapping even TIMES({price}, 2) )

Example images to understand better :
![2021-10-27 16_19_38-Dashboard _ DecisionRules io - Vivaldi](https://user-images.githubusercontent.com/6909701/139085591-64befc0a-78bb-41bf-b170-f05f2a5ab4dd.png)
![2021-10-27 16_17_59-Dashboard _ DecisionRules io - Vivaldi](https://user-images.githubusercontent.com/6909701/139085620-38e0f56e-fa75-41ff-b145-7ba0e51b886c.png)
![2021-10-27 16_18_25-Dashboard _ DecisionRules io - Vivaldi](https://user-images.githubusercontent.com/6909701/139085622-4a188447-2f8e-40b7-b951-a296a94310fb.png)

**Comment by BakuE** [comment]
Hello @t4keo,

Thank you for your question.

I will explain the solution:
You will have a Decision Tables with 1 input and 1 output:
![image](https://user-images.githubusercontent.com/85114488/139135111-8c9a8a65-03f7-499e-9a77-af4448803380.png)

The simple multiply rule:
![image](https://user-images.githubusercontent.com/85114488/139135206-85f4e79a-1fde-4bdd-8ebd-727a7d038fca.png)

You can connect these 2 rules together within the Rule Flow:
Input will be
![image](https://user-images.githubusercontent.com/85114488/139135499-a39d00d5-4b26-43ce-8389-6e81284e8300.png)

then you chain them together (decision table and scripting rule):
![image](https://user-images.githubusercontent.com/85114488/139135548-70676beb-becd-4bcb-9a0d-75839a014c18.png)

If I run it:
![image](https://user-images.githubusercontent.com/85114488/139135693-7b1ebfc1-cb17-42ae-8c8b-7720e69166f4.png)
![image](https://user-images.githubusercontent.com/85114488/139135743-f54145f7-358f-4c14-922f-8cae5b3a252f.png)

In the rule flow you are mapping the outputs on the outputs of the other rules
![image](https://user-images.githubusercontent.com/85114488/139135859-82d4e051-431a-457a-81fb-3431a55dcbd9.png)

I didn't quite understand the thing with TIMES, can you please describe it a little bit more?

If you have any question do not hesitate to contact us at sales@decisionrules.io or here.

Thank you.

Regards,
Erik
