### ISSUE TITLE
Save button disabled

### ISSUE THREAD

**Issue by hoekomnou** [decisiongrid/Issues#12]
I am just trailing the service and I cannot get any rule to save in the table designer. Even just editing a row in the sample rule to the same value still does not show a save button that is enabled. I get the same issue even just creating a blank rule - attempt a rename of the rule and it shows a dialog when you exit the rule name that you have to save it first and then just reverts.

Not sure, I cannot even get past step 1 on the default rules.

![image](https://user-images.githubusercontent.com/87006446/143433141-ae695453-cdef-477d-b5b5-d27c22fb079e.png)

Screenshot show the disabled save button. Even changing the rule state to published does nothing. This is also verifying that there are no issues in the script on the Table Designer - everything is mapped and purple, still nothing. 

![image](https://user-images.githubusercontent.com/87006446/143433010-39c57540-665c-4dad-b6bf-f56b6f804f45.png)

**Comment by ten-petr** [comment]
Hello @hoekomnou ,
We were unable to replicate the error.
In our opinion, the JSON input or output model is not valid.

Please try to click on the "Beautify code" button on the input and output model, in JSON format. This button will perform an explicit validation of your input / output model.

Regards,
Petr

**Comment by ten-petr** [comment]
Closing Issue - no response
