### ISSUE TITLE
Assignament object to output.result returns null output

### ISSUE THREAD

**Issue by AgustinQuetto** [decisiongrid/Issues#13]
Hello Decision Rules Team!

**Describe the bug**
Previously I can assign a variable of type object to the result var of output. Now, it returns null. I already have productive scripts with these type of assignment.

**To Reproduce**
1. Create a new script rule
2. write this example:

```
const _output = {message: "hello world"}
output.result = _output
return output
```

or

```
output.result = {}
return output
```

3. run script
4. check if returns `[null]`

**Expected behavior**
Previously I can assign a variable of type object to the result var of output. Now, it returns null. I already have scripts with these type of assignment.

**Screenshots**
![Uploading Captura de Pantalla 2021-11-29 a la(s) 15.55.21.png…]()

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 96.0.4664.55 (Build official) (x86_64)

**Additional context**
We have the need to assign an object to the return because it is a set of nested information that is manipulated by another API. We have scripted this behavior without any problems, but now it doesn't work.

Thanks!

**Comment by leosrehacek** [comment]
Hello @AgustinQuetto,

we have registered your issue and we are working on the solution.
I will be updating you about the progress.

Regards,
Leos

**Comment by leosrehacek** [comment]
Hello @AgustinQuetto,

the issue is fixed.
Please check it.

If you have any questions please let me know.

Regards,
Leos

**Comment by AgustinQuetto** [comment]
Amazing resolution time. It looks fixed. Thanks @leosrehacek!
