### ISSUE TITLE
**Issue saving a condition with lots of criteria** 

### ISSUE THREAD

**Issue by jlightautino** [decisiongrid/Issues#14]
**Issue saving a condition with lots of criteria** 

**To Reproduce**
When i copied a long list of criteria into one of the conditions - it seems like it cut off some of them
Maybe its user error - but i am sure that i pasted them all in, so please check.

**Expected behavior**
full list updated 

**Screenshots**
This is the full list:
demo | i3 | i8 | mini electric | id. | e- | mustang mach-e | e-transit | mx-30 | leaf | e-nv200 | ariya | e-Transporter | eTransporter | e Transporter | ID.Buzz | ID. Buzz | ID Buzz | ID.Buzz Cargo | ID. Buzz Cargo | ID Buzz Cargo | e-208 | e208 | e 208 | e-2008 | e2008 | e 2008 | e-Rifter | eRifter | e Rifter | e-Traveller | eTraveller | e Traveller

When i saved it at 10.08 i am sure i copied the full list but the full list was not saved - the first 12 were cut off
![image](https://user-images.githubusercontent.com/95855495/145383679-1f9e83dd-33a3-4008-be7c-4dcb6d5a9efe.png)

Saved it again at 10.09 and the full list is saved
![image](https://user-images.githubusercontent.com/95855495/145383756-9ebfa3e8-46e3-4890-8ccf-79f0b8639e4e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser Chrome 
 - Version 96.0.4664.93 (Official Build) (64-bit)

**Comment by ten-petr** [comment]
Hello @jlightautino,
We're trying to reproduce the bug. 

I'll keep you posted.

**Comment by ten-petr** [comment]
Hello @jlightautino,
We tested the functionality in the team and it seems to us that the cell probably remained in edit mode at the time of the first save. At this point, the "Save" button (orange at the bottom right) does not save the value of the edited cell.

We have added a task to the backlog to resolve this ambiguity.

How to avoid this problem?
Before saving the whole rule, please make sure that you have saved individual cells.
