### ISSUE TITLE
Authentication token missing Error code: 401

### ISSUE THREAD

**Issue by DelphiData** [decisiongrid/Issues#15]
![Web capture_30-12-2022_6150_app decisionrules io](https://user-images.githubusercontent.com/9439924/210080052-5fbab49d-f56a-41c6-aa42-d34a8efcf508.jpeg)
![Web capture_30-12-2022_6150_app decisionrules io](https://user-images.githubusercontent.com/9439924/210080068-b3ad7d16-2af5-4306-8ba2-2cf9fb459442.jpeg)

**Comment by leosrehacek** [comment]
Hello @DelphiData, 

thank you for your message.

Please check, if you have any Solver API key.
You can check it in API Keys section.
You have to have at least one key.

Regards,
Leos Rehacek
