### ISSUE TITLE
Python API syntax error

### ISSUE THREAD

**Issue by DelphiData** [decisiongrid/Issues#16]
import decisionrules
import asyncio
import requests

async def solve():        
    solver = decisionrules.SolverApi("***SOLVER API KEY***")
    request_body = {"PrimarySite":"lung","Character":{},"SubLocation":{},"Measure":"8","Change":{},"Age":"35","Finding":"nodule","ReportID":"8475"
    response = await solver.solve(decisionrules.SolverType.RULE, "***RULE ID***", request_body, "STANDARD", 1)
    print(response)
    
    
asyncio.run(solve())

--------------------------------------------------------------------------------------------------------------------------

File "C:\Users\JOEYBA~1\AppData\Local\Temp/ipykernel_3108/3501186646.py", line 9
    response = await solver.solve(decisionrules.SolverType.RULE, "***RULE ID***", request_body, "STANDARD")
    ^
SyntaxError: invalid syntax

**Comment by ten-petr** [comment]
Hello @DelphiData you have syntax error on this line - missing curly bracket:
`request_body = {"PrimarySite":"lung","Character":{},"SubLocation":{},"Measure":"8","Change":{},"Age":"35","Finding":"nodule","ReportID":"8475"`

Code works fine! - tested


```
import asyncio
import decisionrules


async def solve():
    solver = decisionrules.SolverApi("#SOLVER API KEY#")
    request_body = {"PrimarySite":"lung","Character":{},"SubLocation":{},"Measure":"8","Change":{},"Age":"35","Finding":"nodule","ReportID":"8475"}
    response = await solver.solve(decisionrules.SolverType.RULE, "#RULE ID#", request_body, "STANDARD", 1)
    print(response)
asyncio.run(solve())
```
