### ISSUE TITLE
Typescript cannot find declarations

### ISSUE THREAD

**Issue by agile-anthony** [decisiongrid/Issues#18]
**Describe the bug**
Build using the tsc command fails with the following message:
`
src/lib/refinery/rules.ts:12:52 - error TS7016: Could not find a declaration file for module '@decisionrules/decisionrules-js'. '/********/node_modules/@decisionrules/decisionrules-js/dist/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/decisionrules__decisionrules-js` if it exists or add a new declaration (.d.ts) file containing `declare module '@decisionrules/decisionrules-js';`

12 import { CustomDomain, Solver } from '@decisionrules/decisionrules-js'
`

The failed line in the typescript file is:
`import { CustomDomain, Solver } from '@decisionrules/decisionrules-js'`

**To Reproduce**
1. install to project: npm install --save @decisionrules/decisionrules-js
2. Add code following example provided at bottom of "Test Bench" page
3. run tsc command from the project directory

**Expected behavior**
Javascript generated into the designated "dist" directory.

**Screenshots**
See above under description

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.1
 - Browser N/A
 - Version Decisionrules Javascript API v3.0.4, NodeJS v18.12.1, NPM v8.19.2, Typescript tsc v4.9.4

**Smartphone (please complete the following information):**

**Additional context**

**Comment by leosrehacek** [comment]
Hello @agile-anthony,

On our side, we have tested the package and tried to reproduce the error using your steps, but everything works without any problem.

Could you check if you have the package installed correctly? 
Alternatively, please provide a code sample.

Regards,
Leos

**Comment by agile-anthony** [comment]
Thank you for checking on your end. I will continue to check on my side.

The package does appear in my package.json, and does work for Javascript. Only Typescript gives be the message. I’ve even confirmed that the package is in the proper node_modules directory. Maybe it is some setting in my tsconfig.json. Thanks for the quick response
