### ISSUE TITLE
Scripting rule reset to previous step when hit save button

### ISSUE THREAD

**Issue by framled** [decisiongrid/Issues#4]
**Describe the bug**
When I try to create a new scripting rule and click on save button the scripting rule comes back to the previous state.

**To Reproduce**
1. Go to Scripting Rules
1. Click on '+ Scripting Rule'
1. Click on 'Rule Settings' tab
1. Change to Pending State
1. Go to Code Editor
1. Edit code
1. Click on Save button

**Expected behavior**
I expect that new script will the new versión

**Screenshots**
This is the example script, if you try to edit a little bet, like deleting comments.
![Screen Shot 2021-07-12 at 15 35 26](https://user-images.githubusercontent.com/6482001/125345638-c9de8d00-e326-11eb-8987-82e915607a68.png)

Result after editing
![Screen Shot 2021-07-12 at 15 36 54](https://user-images.githubusercontent.com/6482001/125345811-fd211c00-e326-11eb-9e45-8160037451ff.png)

Click Save, come backs to previous state
![Screen Shot 2021-07-12 at 15 37 21](https://user-images.githubusercontent.com/6482001/125345863-0dd19200-e327-11eb-9fd1-c02a43ab6f77.png)

**Desktop (please complete the following information):**
 - OS: Mac OS X Big Sur 11.4
 - Browser: Brave

**Comment by BakuE** [comment]
Hello Framled,

Thank you for reporting the issue that occurred to you. 
Our developers were notified about the issue. The issue might be with the save button, when you change something in the code the save button should change the color to orange (an indication that changes were made).

When the problem will be solved and the patch deployed. 

If you have any other questions, concerns or we can help you with anything please contact us at sales@decisionrules.io

Thank you,

Erik from the DecisionRules team

**Comment by leosrehacek** [comment]
Hello Framled,

The issue was solved and deployed.

Leos from the DecisionRules team
