### ISSUE TITLE
How to specify *strategy* when calling API directly?

### ISSUE THREAD

**Issue by nowickimt** [decisiongrid/Issues#5]
I know that several of the client libraries you have created support the ability to pass in the "strategy" to use when evaluating rules, but how is that done via the API directly?  I've signed up for a DecisionRules trial, and have some rules set up.  I'm trying to use Postman to call the API to solve against those rules, but it appears to be using the "standard" strategy.  I need to be able to use the "first_match" strategy instead.  Can't find anything in the documentation about how to do that.

**Comment by ghost** [comment]
Hi, nowickimt.

Yes, the standard strategy is used as the default one. If you want to use another strategy, you can do so by adding the 'X-Strategy' parameter in the HTTP header.

Valid X-Strategy values for this moment are:

- STANDARD
- ARRAY
- FIRST_MATCH

**Comment by nowickimt** [comment]
Thank you @VojtaMikes --- that worked perfectly!
