### ISSUE TITLE
Add name or labels to api keys.

### ISSUE THREAD

**Issue by framled** [decisiongrid/Issues#7]
**Is your feature request related to a problem? Please describe.**
Is not related to a problem, is an enhancement.

**Describe the solution you'd like**
Add name or labels to api keys, for example we want to use api keys for different projects would be great if can label each api key for fast recognition.

**Describe alternatives you've considered**
I have not considered any alternative

**Additional context**
No

**Comment by BakuE** [comment]
Hello @framled, 

Thank you for the recommendation. I have already added it to our backlog. There might not be an opportunity to directly set the name at API key creation, but it will allow you to rename the API key. 

Thank you.

Regards,
Erik, DecisionRules team
