### ISSUE TITLE
Scripting Rules doesn't allow changes

### ISSUE THREAD

**Issue by roalonsor** [decisiongrid/Issues#9]
When trying to update the script or edit, the "save"  button remains disabled, or behaves erratically. It just doesn't work even when attempting a fork as a workaround,

**To Reproduce**
1. Create a rule script
2. Save and publish'
3. Try to edit or fork, and attempt to save

**Expected behavior**
Update a script rule

**Screenshots**
I
![Screenshot from 2021-09-23 17-03-37](https://user-images.githubusercontent.com/84975010/134576170-81fb534d-b010-4072-b1c7-f7cc5767a8c8.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Brave
 - Version:  1.29.81 Chromium: 93.0.4577.82 (Official Build) (64-bit)

**Additional context**

**Comment by leosrehacek** [comment]
Hi Roalonsor,

Do you have a script without errors? If you have any errors, then the save button is disabled. 
Can you please take a screenshot of your script or write it here?

I have one recommendation for you. At the end of your script, you must write "return output;" for getting a result from the solver.

Regards,
Leos

**Comment by ten-petr** [comment]
@leosrehacek We could make disabled "Save" button more clear in next release. I mean we could add the reason why user cannot save scripting rule.

**Comment by roalonsor** [comment]
@leosrehacek that's correct, I had incomplete code with an error, didn't realize that would prevent me to save the work in progress.
As @ten-petr points out, it would be useful to know why certain functionalities are not working in certain cases
Thanks!
